- diffengine/datasets/hf_dreambooth_datasets.py
- tests/test_datasets/test_hf_dreambooth_datasets.py
DreamBooth Dataset should support `PackInputs` output format.
```
Traceback (most recent call last):
File "/home/ubuntu/.local/lib/python3.8/site-packages/diffengine/.mim/tools/train.py", line 103, in <module>
main()
File "/home/ubuntu/.local/lib/python3.8/site-packages/diffengine/.mim/tools/train.py", line 99, in main
runner.train()
File "/home/ubuntu/.local/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1735, in train
model = self.train_loop.run()  # type: ignore
File "/home/ubuntu/.local/lib/python3.8/site-packages/mmengine/runner/loops.py", line 277, in run
data_batch = next(self.dataloader_iterator)
File "/home/ubuntu/.local/lib/python3.8/site-packages/mmengine/runner/loops.py", line 164, in __next__
data = next(self._iterator)
File …
```
> [BugFix] DreamBooth Dataset

- README.md
- configs/_base_/models/stable_diffusion_v15_textencoder.py
- configs/_base_/schedules/stable_diffusion_50e.py
- configs/lora/README.md
- configs/lora/stable_diffusion_v15_lora_pokemon_blip.py
- configs/lora/stable_diffusion_v15_lora_textencoder_pokemon_blip.py
- configs/stable_diffusion/README.md
- configs/stable_diffusion/stable_diffusion_v15_ema_pokemon_blip.py
- configs/stable_diffusion/stable_diffusion_v15_snr_pokemon_blip.py
- configs/stable_diffusion/stable_diffusion_v15_textencoder_pokemon_blip.py
- configs/stable_diffusion_dreambooth/README.md
- configs/stable_diffusion_xl/stable_diffusion_xl_lora_pokemon_blip.py
- configs/stable_diffusion_xl_dreambooth/README.md
- docs/source/run_guides/inference.md
- docs/source/run_guides/run_dreambooth.md
- docs/source/run_guides/run_dreambooth_xl.md
- docs/source/run_guides/run_lora.md
- docs/source/run_guides/run_sd.md
- docs/source/user_guides/config.md
- setup.py
- tools/demo.py
- tools/demo_lora.py
- tools/model_converters/publish_model2diffusers.py
- add details docs
- seperate stable diffusion and lora dir
- test training all models and show results
- fix model converters and demo
**Before PR**:
> [Feature] Refactor Stable Diffusion and LoRA

- configs/distill_sd_dreambooth/README.md
Environment:
- A6000 Single GPU
- nvcr.io/nvidia/pytorch:23.07-py3
Settings:
- 1k iterations training, (validation 4 images / 100 iterations)
- LoRA (rank=8) / DreamBooth
|  Model   | total time |
| :------: | :--------: |
|  SDV1.5  | 16 m 39 s  |
| Small SD | 11 m 57 s  |
| Tiny SD  | 11 m 17 s  |
**Before PR**:
> [Enhance] Add training time for distill sd

- configs/_base_/datasets/keramer_face_dreambooth.py
- configs/distill_sd_dreambooth/README.md
- configs/distill_sd_dreambooth/small_sd_dreambooth_lora_dog.py
- configs/distill_sd_dreambooth/small_sd_dreambooth_lora_keramer_face.py
- configs/distill_sd_dreambooth/tiny_sd_dreambooth_lora_dog.py
- configs/distill_sd_dreambooth/tiny_sd_dreambooth_lora_keramer_face.py
- configs/stable_diffusion_dreambooth/stable_diffusion_v15_dreambooth_lora_dog.py
- configs/stable_diffusion_dreambooth/stable_diffusion_v21_dreambooth_lora_dog.py
- configs/stable_diffusion_xl_dreambooth/stable_diffusion_xl_dreambooth_lora_dog.py
- configs/stable_diffusion_xl_dreambooth/stable_diffusion_xl_dreambooth_lora_keramer_face.py
- configs/stable_diffusion_xl_dreambooth/stable_diffusion_xl_dreambooth_lora_potatehead.py
- configs/stable_diffusion_xl_dreambooth/stable_diffusion_xl_dreambooth_lora_starbucks.py
- diffengine/datasets/hf_dreambooth_datasets.py
- tests/test_datasets/test_hf_dreambooth_datasets.py
Distill SD was distilled from SG161222/Realistic_Vision_V4.0 on a Subset of recastai/LAION-art-EN-improved-captions dataset. As a result, this model excels in enhancing performance for human faces.
- Add Human face DreamBooth with Distill SD
- Fix DreamBooth bug that create class images with different base model.
**Before PR**:
> [Feature] Human face DreamBooth with Distill SD.

- README.md
> [Fix] Fix README.md

- configs/_base_/datasets/dog_dreambooth_xl.py
- configs/_base_/datasets/fill50k_controlnet_xl.py
- configs/_base_/datasets/keramer_face_dreambooth_xl.py
- configs/_base_/datasets/pokemon_blip_xl.py
- configs/_base_/datasets/potatohead_dreambooth_xl.py
- configs/_base_/datasets/starbucks_dreambooth_xl.py
- configs/stable_diffusion_xl/README.md
- configs/stable_diffusion_xl_controlnet/README.md
- configs/stable_diffusion_xl_controlnet_small/README.md
- configs/stable_diffusion_xl_controlnet_small/stable_diffusion_xl_controlnet_mid_fill50k.py
- configs/stable_diffusion_xl_controlnet_small/stable_diffusion_xl_controlnet_small_fill50k.py
- configs/stable_diffusion_xl_dreambooth/README.md
- configs/stable_diffusion_xl_lora/README.md
- configs/stable_diffusion_xl_lora/stable_diffusion_xl_lora_pokemon_blip.py
- diffengine/models/editors/stable_diffusion_controlnet/stable_diffusion_controlnet.py
- diffengine/models/editors/stable_diffusion_xl_controlnet/stable_diffusion_xl_controlnet.py
- docs/source/run_guides/run_controlnet_xl.md
- docs/source/run_guides/run_dreambooth_xl.md
- docs/source/run_guides/run_lora_xl.md
- docs/source/run_guides/run_sdxl.md
- projects/face_expression/_base_/face_expression_xl_dataset.py
- tests/test_models/test_editors/test_stable_diffusion_controlnet/test_stable_diffusion_controlnet.py
- tests/test_models/test_editors/test_stable_diffusion_xl_controlnet/test_stable_diffusion_xl_controlnet.py
- tools/demo.py
- tools/demo_controlnet.py
- tools/demo_lora.py
[ControlNet Small / Mid](https://huggingface.co/diffusers/controlnet-canny-sdxl-1.0-small)
**Before PR**:
> [Feature] Support ControlNet Small

- diffengine/datasets/__init__.py
- diffengine/datasets/samplers/__init__.py
- diffengine/datasets/samplers/batch_sampler.py
- diffengine/datasets/transforms/__init__.py
- diffengine/datasets/transforms/processing.py
- diffengine/registry.py
- tests/test_datasets/test_samplers/test_batch_sampler.py
- tests/test_datasets/test_transforms/test_processing.py
Multiple input size training like [SDXL](https://arxiv.org/abs/2307.01952) and [NovelAI Aspect Ratio Bucketing](https://github.com/NovelAI/novelai-aspect-ratio-bucketing).
```
dict(type='MultiAspectRatioResizeCenterCrop',
sizes=[
[640, 1536], [768, 1344], [832, 1216], [896, 1152],
[1024, 1024], [1152, 896], [1216, 832], [1344, 768], [1536, 640]
],
interpolation='bilinear'),
sampler=dict(type='DefaultSampler', shuffle=True),
batch_sampler=dict(type='AspectRatioBatchSampler'),
```
**Before PR**:
> [Feature] Support multi aspectratio resize

- README.md
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.
Please describe the motivation of this PR and the goal you want to achieve through this PR.
Please briefly describe what modification is made in this PR.
Please show results.
If this PR introduces a new feature, it is better to list some use cases here and update the documentation.
**Before PR**:
> add sponsor

- .devcontainer/devcontainer.json
- configs/_base_/datasets/pokemon_blip_xl_pre_compute.py
- configs/stable_diffusion_xl/README.md
- configs/stable_diffusion_xl/stable_diffusion_xl_pokemon_blip_pre_compute.py
- diffengine/datasets/__init__.py
- diffengine/datasets/hf_datasets.py
- diffengine/datasets/utils.py
- diffengine/models/editors/stable_diffusion_xl/sdxl_data_preprocessor.py
- diffengine/models/editors/stable_diffusion_xl/stable_diffusion_xl.py
- tests/test_datasets/test_hf_datasets.py
- tests/test_models/test_editors/test_stable_diffusion_xl/test_stable_diffusion_xl.py
Support `Pre compute Text Embeddings` to speedup and reduce memory for training.
**Before PR**:
> [Feature] Pre compute Text Embeddings

- configs/ip_adapter/README.md
- configs/ip_adapter/stable_diffusion_xl_pokemon_blip_ip_adapter_plus.py
> [Enhance] Fix more epochs for IP Adapter Plus

- README.md
- configs/_base_/datasets/fill50k_t2i_adapter_xl.py
- configs/_base_/models/stable_diffusion_xl_t2i_adapter.py
- configs/t2i_adapter/README.md
- configs/t2i_adapter/stable_diffusion_xl_t2i_adapter_fill50k.py
- diffengine/engine/hooks/__init__.py
- diffengine/engine/hooks/t2i_adapter_save_hook.py
- diffengine/models/editors/__init__.py
- diffengine/models/editors/stable_diffusion_controlnet/stable_diffusion_controlnet.py
- diffengine/models/editors/t2i_adapter/__init__.py
- diffengine/models/editors/t2i_adapter/stable_diffusion_xl_t2i_adapter.py
- docs/source/run_guides/run_t2i_adapter.md
- tests/test_engine/test_hooks/test_controlnet_save_hook.py
- tests/test_engine/test_hooks/test_t2i_adapter_save_hook.py
- tests/test_models/test_editors/test_t2i_adapter/test_stable_diffusion_xl_t2i_adapter.py
- tools/demo_adapter.py
[T2I Adapter](https://arxiv.org/abs/2302.08453).
**Before PR**:
> [Feature] Support T2I Adapter

- tools/analysis_tools/show_vae.py
Show VAE encode decode result.
**Before PR**:
> [Feature] Support show vae tool

- .devcontainer/devcontainer.json
- Dockerfile
- README.md
- configs/_base_/datasets/dog_dreambooth_if.py
- configs/_base_/datasets/pokemon_blip_if.py
- configs/_base_/models/deepfloyd_if_l.py
- configs/_base_/models/deepfloyd_if_xl_lora.py
- configs/deepfloyd_if/README.md
- configs/deepfloyd_if/deepfloyd_if_l_pokemon_blip.py
- configs/deepfloyd_if_dreambooth/README.md
- configs/deepfloyd_if_dreambooth/deepfloyd_if_xl_dreambooth_lora_dog.py
- diffengine/datasets/hf_dreambooth_datasets.py
- diffengine/models/editors/__init__.py
- diffengine/models/editors/deepfloyd_if/__init__.py
- diffengine/models/editors/deepfloyd_if/deepfloyd_if.py
- requirements/requirements.txt
- tests/test_models/test_editors/test_deepfloyd_if/test_deepfloyd_if.py
- tools/demo_if.py
- tools/demo_if_lora.py
Support [DeepFloyd IF](https://huggingface.co/docs/diffusers/v0.19.3/api/pipelines/deepfloyd_if)
Stage1 output example
Stage3 output example
Stage1 output example
Stage3 output example
**Before PR**:
> [Feature] Support DeepFloyd IF

- Dockerfile
- configs/stable_diffusion_xl/README.md
- configs/stable_diffusion_xl/stable_diffusion_xl_pokemon_blip_fast.py
- diffengine/engine/hooks/__init__.py
- diffengine/engine/hooks/compile_hook.py
- diffengine/engine/hooks/fast_norm_hook.py
- diffengine/engine/optimizers/__init__.py
- diffengine/engine/optimizers/builder.py
- pyproject.toml
- tests/test_engine/test_hooks/test_compile_hook.py
- tests/test_engine/test_hooks/test_fast_norm_hook.py
- tests/test_engine/test_optimizers/test_optimizer.py
- Support FusedLN and FP16 GN.
|  Model   | total time |
| :------: | :--------: |
|  stable_diffusion_xl_pokemon_blip (fp16)  | 12 m 37 s  |
| stable_diffusion_xl_pokemon_blip_fast | 12 m 10 s  |
**Before PR**:
----
:books: Documentation preview :books:: https://DiffEngine--84.org.readthedocs.build/en/84/
> [Feature] Faster training

- configs/stable_diffusion_xl/README.md
- configs/stable_diffusion_xl/stable_diffusion_xl_pokemon_blip_fast.py
- diffengine/engine/hooks/compile_hook.py
- diffengine/engine/hooks/fast_norm_hook.py
- tests/test_engine/test_hooks/test_compile_hook.py
- tests/test_engine/test_hooks/test_fast_norm_hook.py
Use `torch.compile`. Del `gradient_checkpointing`.
|                  Model                  | total time |
| :-------------------------------------: | :--------: |
| stable_diffusion_xl_pokemon_blip (fp16) | 12 m 37 s  |
|  stable_diffusion_xl_pokemon_blip_fast  |  9 m 47 s  |
Note that `stable_diffusion_xl_pokemon_blip_fast` took a few minutes to compile. We will disregard it.
**Before PR**:
> [Feature] Faster train with torch.compile

- diffengine/engine/hooks/compile_hook.py
|                  Model                  | total time |
| :-------------------------------------: | :--------: |
| stable_diffusion_xl_pokemon_blip_fast | 9 m 47 s  |
|  +compile mode="reduce-overhead”  |  9 m 15 s  |
Note that `mode="reduce-overhead”` creates a strict graph, which means that the validation method cannot be executed.
```
dict(type="CompileHook", compile_unet=True, mode="reduce-overhead”),
```
**Before PR**:
----
:books: Documentation preview :books:: https://DiffEngine--86.org.readthedocs.build/en/86/
> [Enhance] Support compile mode

- README.md
- configs/_base_/datasets/instructpix2pix_xl.py
- configs/_base_/models/stable_diffusion_xl_instruct_pix2pix.py
- configs/instruct_pix2pix/README.md
- configs/instruct_pix2pix/stable_diffusion_xl_instruct_pix2pix.py
- diffengine/models/editors/__init__.py
- diffengine/models/editors/instruct_pix2pix/__init__.py
- diffengine/models/editors/instruct_pix2pix/instruct_pix2pix_xl.py
- docs/source/run_guides/run_instruct_pix2pix.md
- tests/test_models/test_editors/test_instruct_pix2pix/test_instruct_pix2pix.py
[InstructPix2Pix: Learning to Follow Image Editing Instructions](https://arxiv.org/abs/2211.09800)
**Before PR**:
> [Feature] Support InstructPix2Pix

- README.md
- configs/timesteps_bias/README.md
- configs/timesteps_bias/stable_diffusion_xl_pokemon_blip_earlier_bias.py
- configs/timesteps_bias/stable_diffusion_xl_pokemon_blip_later_bias.py
- configs/timesteps_bias/stable_diffusion_xl_pokemon_blip_range_bias.py
- diffengine/models/editors/deepfloyd_if/deepfloyd_if.py
- diffengine/models/editors/distill_sd/distill_sd_xl.py
- diffengine/models/editors/esd/esd_xl.py
- diffengine/models/editors/instruct_pix2pix/instruct_pix2pix_xl.py
- diffengine/models/editors/ip_adapter/ip_adapter_xl.py
- diffengine/models/editors/ssd_1b/ssd_1b.py
- diffengine/models/editors/stable_diffusion/stable_diffusion.py
- diffengine/models/editors/stable_diffusion_controlnet/stable_diffusion_controlnet.py
- diffengine/models/editors/stable_diffusion_xl/stable_diffusion_xl.py
- diffengine/models/editors/stable_diffusion_xl_controlnet/stable_diffusion_xl_controlnet.py
- diffengine/models/editors/t2i_adapter/stable_diffusion_xl_t2i_adapter.py
- diffengine/models/utils/__init__.py
- diffengine/models/utils/timesteps.py
- tests/test_engine/test_hooks/test_compile_hook.py
- tests/test_engine/test_hooks/test_controlnet_save_hook.py
- tests/test_engine/test_hooks/test_fast_norm_hook.py
- tests/test_engine/test_hooks/test_ip_adapter_save_hook.py
- tests/test_engine/test_hooks/test_lora_save_hook.py
- tests/test_engine/test_hooks/test_t2i_adapter_save_hook.py
- tests/test_engine/test_hooks/test_visualization_hook.py
- tests/test_models/test_editors/test_t2i_adapter/test_stable_diffusion_xl_t2i_adapter.py
- tests/test_models/test_utils/test_timesteps.py
[Time Steps Bias](https://github.com/huggingface/diffusers/pull/5094)
**Before PR**:
----
:books: Documentation preview :books:: https://DiffEngine--90.org.readthedocs.build/en/90/
> [Feature] Support TimeSteps Bias

- docs/source/user_guides/dataset_prepare.md
Documentation on how to prepare the dataset for ControlNet.
**Before PR**:
----
:books: Documentation preview :books:: https://DiffEngine--100.org.readthedocs.build/en/100/
> [Docs] ControlNet data prepare

- configs/_base_/datasets/cartoonization_xl.py
- configs/_base_/datasets/low_level_image_process_xl.py
- configs/instruct_pix2pix/README.md
- configs/instruct_pix2pix/stable_diffusion_xl_cartoonization.py
- configs/instruct_pix2pix/stable_diffusion_xl_low_level_image_process.py
- diffengine/datasets/transforms/processing.py
- diffengine/models/editors/instruct_pix2pix/instruct_pix2pix_xl.py
- tests/test_datasets/test_transforms/test_processing.py
[Instruction-tuning Stable Diffusion with InstructPix2Pix](https://huggingface.co/blog/instruction-tuning-sd)
**Before PR**:
----
:books: Documentation preview :books:: https://DiffEngine--103.org.readthedocs.build/en/103/
> [Feature] Supoport Instruction-tuning SDXL

- configs/_base_/models/deepfloyd_if_xl_lora.py
- configs/_base_/models/lcm_xl_lora.py
- configs/_base_/models/small_sd_lora.py
- configs/_base_/models/ssd_1b_lora.py
- configs/_base_/models/stable_diffusion_v15_lora.py
- configs/_base_/models/stable_diffusion_v21_lora.py
- configs/_base_/models/stable_diffusion_xl_loha.py
- configs/_base_/models/stable_diffusion_xl_lokr.py
- configs/_base_/models/stable_diffusion_xl_lora.py
- configs/_base_/models/tiny_sd_lora.py
- configs/_base_/models/wuerstchen_prior_lora.py
I had a wrong understanding of the relationship between `alpha` and `scaling` in peft and have corrected it. `alpha` must be the same value as `r` in order to match diffusers.
**Before PR**:
----
:books: Documentation preview :books:: https://DiffEngine--104.org.readthedocs.build/en/104/
> [Fix] LoRA default alpha

- Dockerfile
- configs/stable_diffusion_xl/README.md
- configs/stable_diffusion_xl/stable_diffusion_xl_pokemon_blip_xformers.py
- diffengine/models/editors/deepfloyd_if/deepfloyd_if.py
- diffengine/models/editors/distill_sd/distill_sd_xl.py
- diffengine/models/editors/esd/esd_xl.py
- diffengine/models/editors/lcm/lcm_xl.py
- diffengine/models/editors/ssd_1b/ssd_1b.py
- diffengine/models/editors/stable_diffusion/stable_diffusion.py
- diffengine/models/editors/stable_diffusion_controlnet/stable_diffusion_controlnet.py
- diffengine/models/editors/stable_diffusion_xl/stable_diffusion_xl.py
- diffengine/models/editors/stable_diffusion_xl_controlnet/stable_diffusion_xl_controlnet.py
- diffengine/models/editors/t2i_adapter/stable_diffusion_xl_t2i_adapter.py
Support xformers. https://github.com/facebookresearch/xformers
Environment:
- A6000 Single GPU
- nvcr.io/nvidia/pytorch:23.10-py3
Settings:
- 1epoch training.
|                   Model                   | total time |
| :---------------------------------------: | :--------: |
|  stable_diffusion_xl_pokemon_blip (fp16)  | 12 m 37 s  |
| stable_diffusion_xl_pokemon_blip_xformers |  10 m 6 s  |
|   stable_diffusion_xl_pokemon_blip_fast   |  9 m 47 s  |
**Before PR**:
----
:books: Documentation preview :books:: https://DiffEngine--105.org.readthedocs.build/en/105/
> [Feature] Support xformers

- Dockerfile
- configs/stable_diffusion_xl/README.md
- configs/stable_diffusion_xl/stable_diffusion_xl_pokemon_blip_colossal.py
- configs/stable_diffusion_xl/stable_diffusion_xl_pokemon_blip_deepspeed_stage2.py
- configs/stable_diffusion_xl/stable_diffusion_xl_pokemon_blip_deepspeed_stage3.py
- pyproject.toml
[MMEngine TRAINING BIG MODELS](https://mmengine.readthedocs.io/en/latest/common_usage/large_model_training.html)
Environment:
- A100 x 4 GPUs
- nvcr.io/nvidia/pytorch:23.11-py3
Settings:
- 1epoch training.
|                           Model                           | total time |
| :-------------------------------------------------------: | :--------: |
|       stable_diffusion_xl_pokemon_blip_fast (BS=4)        |  1 m 6 s   |
| stable_diffusion_xl_pokemon_blip_deepspeed_stage3 (BS=8)  |  1 m 5 s   |
| stable_diffusion_xl_pokemon_blip_deepspeed_stage2 (BS=8)  |    58 s    |
| stable_diffusion_xl_pokemon_blip_colossal (stage=2, BS=8) |    58s     |
**Before PR**:
----
:books: Documentation preview :books:: https://DiffEngine--109.org.readthedocs.build/en/109/
> [Feature] Support DeepSpeed/CorossalAI

- configs/_base_/datasets/dog_inpaint_multiple_mask.py
- configs/stable_diffusion_inpaint/README.md
- configs/stable_diffusion_inpaint/stable_diffusion_inpaint_dog_multi_mask.py
- diffengine/datasets/hf_dreambooth_datasets.py
- diffengine/datasets/transforms/__init__.py
- diffengine/datasets/transforms/processing.py
- diffengine/datasets/transforms/wrappers.py
- diffengine/engine/hooks/peft_save_hook.py
- diffengine/models/editors/pixart_alpha/pixart_alpha.py
- diffengine/models/editors/stable_diffusion_xl_controlnet/stable_diffusion_xl_controlnetxs.py
- tests/test_datasets/test_hf_dreambooth_datasets.py
- tests/test_datasets/test_transforms/test_processing.py
- tests/test_datasets/test_transforms/test_wrappers.py
- tests/test_models/test_editors/test_stable_diffusion_xl_controlnet/test_stable_diffusion_xl_controlnetxs.py
RandomChoice for random mask inpainting.
```
dict(type="RandomChoice",
transforms=[
[dict(
type="LoadMask",
mask_mode="irregular",
mask_config=dict(
num_vertices=(4, 10),
max_angle=6.0,
length_range=(20, 200),
brush_width=(10, 100),
area_ratio_range=(0.15, 0.65)))],
[dict(
type="LoadMask",
mask_mode="irregular",
mask_config=dict(
num_vertices=(1, 5),
max_angle=6.0,
length_range=(40, 450),
brush_width=(20, 250),
area_ratio_range=(0.15, 0.65)))],
[dict(
type="LoadMask",
mask_mode="irregular",
mask_config=dict(
num_vertices=(4, 70),
max_angle=6.0,
length_range=(15, 100),
brush_width=(5, 20),
area_ratio_range=(0.15, 0.65)))],
[dict(
type="LoadMask",
mask_mode="bbox",
mask_config=dict(
max_bbox_shape=(150, 150),
max_bbox_delta=50,
min_margin=0))],
[dict(
type="LoadMask",
mask_mode="bbox", …
```
> [Feature] Support RandomChoice for random mask

- configs/_base_/datasets/dog_inpaint_multiple_mask.py
- diffengine/datasets/transforms/__init__.py
- diffengine/datasets/transforms/dump_image.py
- diffengine/datasets/transforms/processing.py
- tests/test_datasets/test_transforms/test_processing.py
masked image = image * mask -> image * (mask < 0.5)
**Before PR**:
----
📚 Documentation preview 📚: https://DiffEngine--114.org.readthedocs.build/en/114/
> [Bugfix] Inpaint masked image

- configs/ip_adapter/README.md
- configs/ip_adapter/stable_diffusion_xl_pokemon_blip_ip_adapter_plus_pretrained.py
- diffengine/engine/hooks/ip_adapter_save_hook.py
- diffengine/models/archs/__init__.py
- diffengine/models/archs/ip_adapter.py
- diffengine/models/editors/ip_adapter/ip_adapter_xl.py
- tests/test_engine/test_hooks/test_ip_adapter_save_hook.py
- tests/test_models/test_archs.py
- tests/test_models/test_editors/test_ip_adapter/test_ip_adapter.py
- tests/test_models/test_editors/test_ip_adapter/test_ip_adapter_plus.py
Finetune pretrained IP-Adapter
**Before PR**:
----
📚 Documentation preview 📚: https://DiffEngine--115.org.readthedocs.build/en/115/
> [Feature] Support Finetune pretrained IP-Adapter

- README.md
- configs/_base_/datasets/pokemon_blip_kandinsky_v3.py
- configs/_base_/models/kandinsky_v3.py
- configs/kandinsky_v3/README.md
- configs/kandinsky_v3/kandinsky_v3_pokemon_blip.py
- diffengine/models/editors/kandinsky/__init__.py
- diffengine/models/editors/kandinsky/kandinskyv3.py
- tests/test_models/test_editors/test_kandinsky/test_kandinsky_v3.py
- tools/model_converters/publish_model2diffusers.py
[Kandinsky 3](https://ai-forever.github.io/Kandinsky-3/)
**Before PR**:
----
📚 Documentation preview 📚: https://DiffEngine--117.org.readthedocs.build/en/117/
> [Feature] Support Kandinskyv3

- README.md
- diffengine/configs/_base_/datasets/pickascore_xl.py
- diffengine/configs/_base_/models/stable_diffusion_xl_dpo.py
- diffengine/configs/diffusion_dpo/README.md
- diffengine/configs/diffusion_dpo/stable_diffusion_xl_dpo_pickascore.py
- diffengine/datasets/__init__.py
- diffengine/datasets/hf_dpo_datasets.py
- diffengine/datasets/transforms/__init__.py
- diffengine/datasets/transforms/processing.py
- diffengine/models/editors/__init__.py
- diffengine/models/editors/stable_diffusion_xl_dpo/__init__.py
- diffengine/models/editors/stable_diffusion_xl_dpo/sdxl_dpo_data_preprocessor.py
- diffengine/models/editors/stable_diffusion_xl_dpo/stable_diffusion_xl_dpo.py
- diffengine/models/losses/debias_estimation_loss.py
- diffengine/models/losses/hubar_loss.py
- diffengine/models/losses/l2_loss.py
- diffengine/models/losses/snr_l2_loss.py
- tests/test_datasets/test_transforms/test_processing.py
- tests/test_models/test_editors/test_stable_diffusion_xl_dpo/test_stable_diffusion_xl_dpo.py
- tests/test_models/test_losses.py
[Diffusion Model Alignment Using Direct Preference Optimization](https://arxiv.org/abs/2311.12908)
**Before PR**:
----
📚 Documentation preview 📚: https://DiffEngine--124.org.readthedocs.build/en/124/
> [Feature] Support Diffusion DPO

- .devcontainer/devcontainer.json
- .github/workflows/build.yml
- Dockerfile
- diffengine/configs/_base_/datasets/face_spiga_controlnet.py
- diffengine/configs/_base_/datasets/fill50k_controlnet.py
- diffengine/configs/_base_/datasets/fill50k_controlnet_xl.py
- diffengine/configs/_base_/datasets/fill50k_t2i_adapter_xl.py
- diffengine/configs/ip_adapter/README.md
- diffengine/configs/stable_diffusion_controlnet/README.md
- diffengine/configs/stable_diffusion_xl/README.md
- diffengine/configs/stable_diffusion_xl_controlnet/README.md
- diffengine/configs/stable_diffusion_xl_controlnet_small/README.md
- diffengine/configs/t2i_adapter/README.md
- diffengine/engine/hooks/visualization_hook.py
- diffengine/models/archs/ip_adapter.py
- docs/source/run_guides/run_controlnet.md
- docs/source/run_guides/run_controlnet_xl.md
- docs/source/run_guides/run_ip_adapter.md
- docs/source/run_guides/run_t2i_adapter.md
- projects/controlnetxs/README.md
- pyproject.toml
- tests/test_engine/test_hooks/test_visualization_hook.py
Update libs.
**Before PR**:
----
📚 Documentation preview 📚: https://DiffEngine--129.org.readthedocs.build/en/129/
> [Feat] Update libs

- diffengine/models/editors/ip_adapter/ip_adapter_xl.py
Fix based on https://github.com/huggingface/diffusers/pull/6573.
```
encoder_hidden_states, ip_hidden_states = encoder_hidden_states
```
**Before PR**:
----
📚 Documentation preview 📚: https://DiffEngine--131.org.readthedocs.build/en/131/
> [Bugfix] Fix IP-Adapter training

- diffengine/models/editors/amused/amused.py
- diffengine/models/editors/distill_sd/distill_sd_xl.py
- diffengine/models/editors/instruct_pix2pix/instruct_pix2pix_xl.py
- diffengine/models/editors/ip_adapter/ip_adapter_xl.py
- diffengine/models/editors/kandinsky/kandinskyv22_decoder.py
- diffengine/models/editors/kandinsky/kandinskyv3.py
- diffengine/models/editors/lcm/lcm_xl.py
- diffengine/models/editors/pixart_alpha/pixart_alpha.py
- diffengine/models/editors/ssd_1b/ssd_1b.py
- diffengine/models/editors/stable_diffusion/stable_diffusion.py
- diffengine/models/editors/stable_diffusion_controlnet/stable_diffusion_controlnet.py
- diffengine/models/editors/stable_diffusion_inpaint/stable_diffusion_inpaint.py
- diffengine/models/editors/stable_diffusion_xl/stable_diffusion_xl.py
- diffengine/models/editors/stable_diffusion_xl_controlnet/stable_diffusion_xl_controlnet.py
- diffengine/models/editors/stable_diffusion_xl_dpo/stable_diffusion_xl_dpo.py
- diffengine/models/editors/stable_diffusion_xl_inpaint/stable_diffusion_xl_inpaint.py
- diffengine/models/editors/t2i_adapter/stable_diffusion_xl_t2i_adapter.py
VAEs have high memory requirements, especially when processing large batches of data. To reduce the memory usage, we can use a VAE batch forward technique.
Based on https://github.com/huggingface/diffusers/blob/v0.26.2/examples/research_projects/controlnet/train_controlnet_webdataset.py#L1306-L1309 
**Before PR**:
----
📚 Documentation preview 📚: https://DiffEngine--132.org.readthedocs.build/en/132/
> [Feature] Support VAE batch

- diffengine/configs/ip_adapter/README.md
- diffengine/configs/ip_adapter/stable_diffusion_xl_pokemon_blip_ip_adapter_plus_dinov2_giant_lasthidden.py
- diffengine/models/editors/ip_adapter/ip_adapter_xl.py
- diffengine/models/editors/ip_adapter/pipeline.py
- tests/test_models/test_editors/test_ip_adapter/test_ip_adapter_plus.py
CLIP Image encoder skips last hidden layer. But DINOv2 can use it.
**Before PR**:
----
📚 Documentation preview 📚: https://DiffEngine--134.org.readthedocs.build/en/134/
> [Featu] Support IP-Adapter Last hidden

- diffengine/configs/_base_/datasets/pokemon_blip_kandinsky_prior.py
- diffengine/configs/_base_/datasets/pokemon_blip_xl_ip_adapter_siglip_384.py
- diffengine/configs/ip_adapter/README.md
- diffengine/configs/ip_adapter/stable_diffusion_xl_pokemon_blip_ip_adapter_plus_siglip.py
- diffengine/datasets/transforms/processing.py
The [IP-Adapter](https://arxiv.org/abs/2308.06721) support the [SigLIP](https://arxiv.org/abs/2303.15343) Image encoder.
**Before PR**:
----
📚 Documentation preview 📚: https://DiffEngine--135.org.readthedocs.build/en/135/
> [Feat] Support IP-Adapter SigLIP
