- configs/stable_diffusion/stable_diffusion_v15_snr_pokemon_blip.py
- diffengine/models/__init__.py
- diffengine/models/editors/stable_diffusion/stable_diffusion.py
- diffengine/models/losses/__init__.py
- diffengine/models/losses/l2_loss.py
- diffengine/models/losses/snr_l2_loss.py
- tests/test_models/test_losses.py
paper: https://arxiv.org/abs/2303.09556
**Before PR**:
> [Feature] SNR weighting gamma L2 loss

- MANIFEST.in
- configs/_base_/datasets/pokemon_blip.py
- configs/_base_/default_runtime.py
- docs/source/run.md
- setup.py
- tools/demo.py
- tools/model_converters/publish_model2diffusers.py
Add inference demo + convert scripts for diffusers.
**Before PR**:
> [Feature] Add inference demo

- configs/stable_diffusion/stable_diffusion_v15_ema_pokemon_blip.py
- diffengine/engine/hooks/__init__.py
- diffengine/engine/hooks/unet_ema_hook.py
- tests/test_engine/test_hooks/test_unet_ema_hook.py
- tools/train.py
Unet EMA training.
**Before PR**:
> [Feature] Add Unet EMA training

- configs/_base_/datasets/pokemon_blip.py
- configs/_base_/models/stable_diffusion_v15_lora.py
- configs/stable_diffusion/stable_diffusion_v15_lora_pokemon_blip.py
- diffengine/engine/hooks/__init__.py
- diffengine/engine/hooks/lora_save_hook.py
- diffengine/engine/hooks/sd_checkpoint_hook.py
- diffengine/models/archs/__init__.py
- diffengine/models/archs/lora.py
- diffengine/models/editors/stable_diffusion/stable_diffusion.py
- setup.py
- tests/test_engine/test_hooks/test_lora_save_hook.py
- tests/test_engine/test_hooks/test_sd_checkpoint_hook.py
> [Feature] Add LoRA

- .github/workflows/build.yml
- configs/_base_/models/stable_diffusion_v15_lora_textencoder.py
- configs/stable_diffusion/stable_diffusion_v15_lora_textencoder_pokemon_blip.py
- diffengine/engine/hooks/lora_save_hook.py
- diffengine/engine/hooks/unet_ema_hook.py
- diffengine/engine/hooks/visualization_hook.py
- diffengine/models/archs/__init__.py
- diffengine/models/archs/lora.py
- diffengine/models/editors/stable_diffusion/stable_diffusion.py
- docs/source/run.md
- tests/test_engine/test_hooks/test_lora_save_hook.py
- tests/test_models/test_archs.py
- tests/test_models/test_editors/test_stable_diffusion/test_stable_diffusion.py
- tests/test_models/test_losses.py
- tools/demo_lora.py
> [Feature] Support train text_encoder

- configs/_base_/datasets/dog_dreambooth.py
- configs/_base_/default_runtime.py
- configs/_base_/schedules/stable_diffusion_v15_2k.py
- configs/stable_diffusion/stable_diffusion_v15_dreambooth_lora_dog.py
- diffengine/datasets/__init__.py
- diffengine/datasets/hf_dreambooth_datasets.py
- diffengine/engine/hooks/visualization_hook.py
- diffengine/models/editors/stable_diffusion/stable_diffusion.py
- diffengine/models/editors/stable_diffusion_xl/stable_diffusion_xl.py
- diffengine/models/losses/l2_loss.py
- diffengine/models/losses/snr_l2_loss.py
- docs/source/run_sd.md
- requirements/requirements.txt
- tests/test_engine/test_hooks/test_visualization_hook.py
- tests/test_models/test_editors/test_stable_diffusion/test_stable_diffusion.py
- tests/test_models/test_editors/test_stable_diffusion_xl/test_stable_diffusion_xl.py
- tests/test_models/test_losses.py
> [Feature] Support DreamBooth

- diffengine/datasets/hf_dreambooth_datasets.py
- diffengine/datasets/transforms/processing.py
- tests/test_datasets/test_hf_dreambooth_datasets.py
- tests/test_datasets/test_transforms/test_processing.py
> [Bugfix] crop top left calc

- diffengine/datasets/transforms/formatting.py
- diffengine/engine/hooks/visualization_hook.py
- diffengine/models/editors/stable_diffusion/__init__.py
- diffengine/models/editors/stable_diffusion/sd_data_preprocessor.py
- diffengine/models/editors/stable_diffusion/stable_diffusion.py
- diffengine/models/editors/stable_diffusion_xl/__init__.py
- diffengine/models/editors/stable_diffusion_xl/sdxl_data_preprocessor.py
- diffengine/models/editors/stable_diffusion_xl/stable_diffusion_xl.py
- tests/test_datasets/test_transforms/test_formatting.py
- tests/test_engine/test_hooks/test_lora_save_hook.py
- tests/test_engine/test_hooks/test_visualization_hook.py
- tests/test_models/test_archs.py
- tests/test_models/test_editors/test_stable_diffusion/test_stable_diffusion.py
- tests/test_models/test_editors/test_stable_diffusion_xl/test_stable_diffusion_xl.py
> [Feature] Support DDP

- README.md
- docs/source/dataset_prepare.md
- docs/source/index.rst
> [Docs] prepare dataset

- docs/source/get_started.md
> [Docs] Update get started

- README.md
- diffengine/models/editors/stable_diffusion/stable_diffusion.py
- diffengine/models/editors/stable_diffusion_xl/stable_diffusion_xl.py
- tests/test_models/test_editors/test_stable_diffusion/test_stable_diffusion.py
- tests/test_models/test_editors/test_stable_diffusion_xl/test_stable_diffusion_xl.py
Support gradient checkpointing to save Memory.
**Before PR**:
> [Feature] Support gradient checkpointing

- diffengine/version.py
> [Bump] v0.1.1

- README.md
- configs/stable_diffusion/README.md
- configs/stable_diffusion_dreambooth/README.md
- configs/stable_diffusion_lora/README.md
- configs/stable_diffusion_xl/README.md
- configs/stable_diffusion_xl_lora/README.md
- docs/source/get_started.md
- docs/source/run_guides/inference.md
- docs/source/run_guides/run_dreambooth.md
- docs/source/run_guides/run_dreambooth_xl.md
- docs/source/run_guides/run_lora.md
- docs/source/run_guides/run_lora_xl.md
- docs/source/run_guides/run_sd.md
- docs/source/run_guides/run_sdxl.md
Related issue: https://github.com/okotaku/diffengine/issues/24
**Before PR**:
> [Enhance] Update README

- configs/_base_/models/small_sd_lora.py
- configs/_base_/models/tiny_sd_lora.py
- configs/distill_sd_dreambooth/README.md
- configs/distill_sd_dreambooth/small_sd_dreambooth_lora_dog.py
- configs/distill_sd_dreambooth/tiny_sd_dreambooth_lora_dog.py
- requirements/requirements.txt
- tools/demo.py
- tools/demo_lora.py
[On Architectural Compression of Text-to-Image Diffusion Models](https://arxiv.org/abs/2305.15798)
Support Distill SD DreamBooth.
Note that the result of tiny sd is not good.
**Before PR**:
> [Feature] Support Distill SD DreamBooth

- diffengine/version.py
> [Bump] v0.1.2

- diffengine/version.py
> [Bump] v0.1.3

- .readthedocs.yaml
- docs/source/api.rst
- docs/source/conf.py
- requirements/readthedocs.txt
> [Feature] api docs

- configs/_base_/datasets/dog_dreambooth.py
- configs/_base_/datasets/dog_dreambooth_xl.py
- configs/_base_/datasets/keramer_face_dreambooth.py
- configs/_base_/datasets/keramer_face_dreambooth_xl.py
- configs/_base_/datasets/potatohead_dreambooth_xl.py
- configs/_base_/datasets/starbucks_dreambooth_xl.py
- configs/distill_sd_dreambooth/small_sd_dreambooth_lora_keramer_face.py
- configs/distill_sd_dreambooth/tiny_sd_dreambooth_lora_keramer_face.py
This bug cause memory issue when save checkpoint.
**Before PR**:
> [Bugfix] Delete LoRA EMA

- MANIFEST.in
- README.md
- setup.py
The logo is created by [Ideogram](https://ideogram.ai/).
https://ideogram.ai/g/3k0v1uQ4S5m3EfT7I_2zOg/1
**Before PR**:
> [Feature] Add logo from Ideogram

- MANIFEST.in
- README.md
- setup.py
> Revert "[Feature] Add logo from Ideogram"

- README.md
- projects/face_expression/README.md
- projects/face_expression/_base_/face_expression_dataset.py
- projects/face_expression/_base_/face_expression_xl_dataset.py
- projects/face_expression/stable_diffusion_v15_lora_face_expression.py
- projects/face_expression/stable_diffusion_xl_lora_face_expression.py
Support Face Expression LoRA
Note that training failed. We should improve SDXL LoRA training.
**Before PR**:
> [Project] Face Expression

- diffengine/datasets/transforms/dump_image.py
- projects/README.md
- projects/face_expression/README.md
- projects/face_expression/_base_/face_expression_xl_dataset.py
- projects/face_expression/stable_diffusion_xl_lora_face_expression.py
Fix poor results of SDXL LoRA in the face expression project.
**Before PR**:
> [Enhance] Update face expression project sdxl lora

- diffengine/datasets/hf_controlnet_datasets.py
- diffengine/datasets/hf_datasets.py
- diffengine/datasets/hf_dreambooth_datasets.py
- diffengine/datasets/transforms/dump_image.py
- projects/tohoku_zunko_project/README.md
- projects/tohoku_zunko_project/_base_/zunko_dreambooth.py
- projects/tohoku_zunko_project/_base_/zunko_dreambooth_xl.py
- projects/tohoku_zunko_project/anythingv5_dreambooth_lora_zunko.py
- projects/tohoku_zunko_project/counterfeit_xl_dreambooth_lora_zunko.py
- projects/tohoku_zunko_project/stable_diffusion_v15_dreambooth_lora_zunko.py
- projects/tohoku_zunko_project/stable_diffusion_xl_dreambooth_lora_zunko.py
[Tohoku Zunko Zundamon Project](https://zunko.jp/)
Prompt is `A photo of sks character in a bucket`.
Prompt is `1girl, sks, in a bucket`.
Prompt is `A photo of sks character in a bucket`.
Prompt is `1girl, sks, in a bucket`.
**Before PR**:
> [Feature] Support zunko lora projects

- configs/_base_/datasets/google_backpack_dreambooth_xl.py
- configs/stable_diffusion_xl_dreambooth/README.md
- configs/stable_diffusion_xl_dreambooth/stable_diffusion_xl_dreambooth_lora_google_backpack.py
- diffengine/datasets/hf_dreambooth_datasets.py
- diffengine/datasets/transforms/dump_image.py
- requirements/requirements.txt
Support https://huggingface.co/datasets/google/dreambooth
**Before PR**:
> [Feature] Support google/dreambooth datasets

- .devcontainer/devcontainer.json
- .gitignore
- Dockerfile
> [Enhance] Support devcontainer

- requirements/requirements.txt
- tests/test_engine/test_hooks/test_lora_save_hook.py
> [Enhance] Update libs

- README.md
- configs/_base_/datasets/pokemon_blip_xl_ip_adapter.py
- configs/_base_/models/stable_diffusion_xl_ip_adapter.py
- configs/ip_adapter/README.md
- configs/ip_adapter/stable_diffusion_xl_pokemon_blip_ip_adapter.py
- diffengine/datasets/transforms/__init__.py
- diffengine/datasets/transforms/processing.py
- diffengine/engine/hooks/__init__.py
- diffengine/engine/hooks/ip_adapter_save_hook.py
- diffengine/engine/hooks/visualization_hook.py
- diffengine/models/archs/__init__.py
- diffengine/models/archs/ip_adapter.py
- diffengine/models/archs/lora.py
- diffengine/models/editors/__init__.py
- diffengine/models/editors/ip_adapter/__init__.py
- diffengine/models/editors/ip_adapter/image_projection.py
- diffengine/models/editors/ip_adapter/ip_adapter_xl.py
- diffengine/models/editors/ip_adapter/ip_adapter_xl_data_preprocessor.py
- docs/source/run_guides/run_ip_adapter.md
- tests/test_datasets/test_transforms/test_processing.py
- tests/test_engine/test_hooks/test_ip_adapter_save_hook.py
- tests/test_engine/test_hooks/test_visualization_hook.py
- tests/test_models/test_archs.py
- tests/test_models/test_editors/test_ip_adapter/test_ip_adapter.py
- tools/demo_diffengine.py
[IP-Adapter: Text Compatible Image Prompt Adapter for Text-to-Image Diffusion Models](https://arxiv.org/abs/2308.06721)
**Before PR**:
> [Feature] IP Adapter

- configs/_base_/models/stable_diffusion_xl_ip_adapter_plus.py
- configs/ip_adapter/README.md
- configs/ip_adapter/stable_diffusion_xl_pokemon_blip_ip_adapter_plus.py
- diffengine/models/editors/ip_adapter/__init__.py
- diffengine/models/editors/ip_adapter/ip_adapter_xl.py
- diffengine/models/editors/ip_adapter/resampler.py
- tests/test_models/test_editors/test_ip_adapter/test_ip_adapter_plus.py
IP Adapter Plus from original repo. https://github.com/tencent-ailab/IP-Adapter/tree/main
**Before PR**:
> [Feature] Support IP Adapter Plus

- diffengine/models/editors/ip_adapter/ip_adapter_xl.py
- diffengine/models/editors/stable_diffusion/stable_diffusion.py
- diffengine/models/editors/stable_diffusion_controlnet/stable_diffusion_controlnet.py
- diffengine/models/editors/stable_diffusion_xl/stable_diffusion_xl.py
- diffengine/models/editors/stable_diffusion_xl_controlnet/stable_diffusion_xl_controlnet.py
- tests/test_models/test_editors/test_ip_adapter/test_ip_adapter.py
- tests/test_models/test_editors/test_ip_adapter/test_ip_adapter_plus.py
- tests/test_models/test_editors/test_stable_diffusion/test_stable_diffusion.py
- tests/test_models/test_editors/test_stable_diffusion_controlnet/test_stable_diffusion_controlnet.py
- tests/test_models/test_editors/test_stable_diffusion_xl/test_stable_diffusion_xl.py
- tests/test_models/test_editors/test_stable_diffusion_xl_controlnet/test_stable_diffusion_xl_controlnet.py
> [Feature] Support negative prompt for inference

- configs/_base_/datasets/gogh_esd_xl.py
- configs/_base_/models/stable_diffusion_xl_esd.py
- configs/esd/README.md
- configs/esd/stable_diffusion_xl_gogh_esd.py
- diffengine/datasets/__init__.py
- diffengine/datasets/hf_controlnet_datasets.py
- diffengine/datasets/hf_datasets.py
- diffengine/datasets/hf_dreambooth_datasets.py
- diffengine/datasets/hf_esd_datasets.py
- diffengine/datasets/utils.py
- diffengine/models/editors/__init__.py
- diffengine/models/editors/esd/__init__.py
- diffengine/models/editors/esd/esd_xl.py
- diffengine/models/editors/esd/esd_xl_data_preprocessor.py
- diffengine/models/editors/ip_adapter/ip_adapter_xl.py
- diffengine/models/editors/stable_diffusion/stable_diffusion.py
- diffengine/models/editors/stable_diffusion_controlnet/stable_diffusion_controlnet.py
- diffengine/models/editors/stable_diffusion_xl/stable_diffusion_xl.py
- diffengine/models/editors/stable_diffusion_xl_controlnet/stable_diffusion_xl_controlnet.py
- diffengine/models/editors/t2i_adapter/stable_diffusion_xl_t2i_adapter.py
- tests/test_datasets/test_hf_esd_datasets.py
- tests/test_models/test_editors/test_esd/test_esd.py
- tests/test_models/test_editors/test_ip_adapter/test_ip_adapter.py
- tests/test_models/test_editors/test_ip_adapter/test_ip_adapter_plus.py
- tests/test_models/test_editors/test_stable_diffusion/test_stable_diffusion.py
- tests/test_models/test_editors/test_stable_diffusion_controlnet/test_stable_diffusion_controlnet.py
- tests/test_models/test_editors/test_stable_diffusion_xl/test_stable_diffusion_xl.py
- tests/test_models/test_editors/test_stable_diffusion_xl_controlnet/test_stable_diffusion_xl_controlnet.py
- tests/test_models/test_editors/test_t2i_adapter/test_stable_diffusion_xl_t2i_adapter.py
[Erasing Concepts from Diffusion Models](https://arxiv.org/abs/2303.07345)
SDXL output
ESD output
**Before PR**:
> [Feature] Support Erasing Concepts from Diffusion Models

- diffengine/models/archs/__init__.py
- diffengine/models/archs/ip_adapter.py
- diffengine/models/editors/ip_adapter/__init__.py
- diffengine/models/editors/ip_adapter/ip_adapter_pipeline.py
- diffengine/models/editors/ip_adapter/ip_adapter_xl.py
- tests/test_models/test_archs.py
- tests/test_models/test_editors/test_ip_adapter/test_ip_adapter_pipeline.py
- tests/test_models/test_editors/test_ip_adapter/test_ip_adapter_plus_pipeline.py
> [Feature] Support IP Adapter Pipeline for Inference

- diffengine/version.py
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.
Please describe the motivation of this PR and the goal you want to achieve through this PR.
Please briefly describe what modification is made in this PR.
Please show results.
If this PR introduces a new feature, it is better to list some use cases here and update the documentation.
**Before PR**:
> [Bump] v0.2.0

- diffengine/version.py
> [Bump] v0.2.1

- README.md
- configs/distill_sd/RAEDME.md
- configs/distill_sd_dreambooth/README.md
- configs/stable_diffusion_controlnet/README.md
- configs/stable_diffusion_dreambooth/README.md
- configs/stable_diffusion_xl_controlnet/README.md
- configs/stable_diffusion_xl_dreambooth/README.md
Add model zoo in README.
**Before PR**:
> [Enhance] Add model zoo

- diffengine/models/editors/ip_adapter/ip_adapter_xl.py
Support IP Adapter Batch Size>1.
**Before PR**:
> [Enhance] Support IP Adapter Batch Size>1

- .github/workflows/docs.yml
- README.md
- configs/distill_sd/README.md
- configs/distill_sd_dreambooth/README.md
- configs/stable_diffusion_xl_controlnet_small/README.md
Add links of blog post.
**Before PR**:
----
:books: Documentation preview :books:: https://readthedocs-preview--82.org.readthedocs.build/en/82/
> [Enhance] Add blog post

- .github/workflows/docs.yml
- README.md
- configs/_base_/models/distill_ssd_1b.py
- configs/_base_/models/distill_ssd_1b_from_sdxl.py
- configs/_base_/models/ssd_1b_lora.py
- configs/ssd_1b/README.md
- configs/ssd_1b/ssd_1b_distill_from_sdxl_pokemon_blip.py
- configs/ssd_1b/ssd_1b_distill_pokemon_blip.py
- configs/ssd_1b_dreambooth/README.md
- configs/ssd_1b_dreambooth/ssd_1b_dreambooth_lora_dog.py
- diffengine/models/editors/__init__.py
- diffengine/models/editors/ssd_1b/__init__.py
- diffengine/models/editors/ssd_1b/ssd_1b.py
- tests/test_models/test_editors/test_ssd_1b/test_ssd_1b.py
Support [SSD-1B](https://blog.segmind.com/introducing-segmind-ssd-1b/).
**Before PR**:
----
:books: Documentation preview :books:: https://diffengine--83.org.readthedocs.build/en/83/
> [Feature] Support SSD-1B

- diffengine/engine/hooks/fast_norm_hook.py
- tests/test_engine/test_hooks/test_fast_norm_hook.py
Related PR: https://github.com/okotaku/diffengine/pull/84
**Before PR**:
----
:books: Documentation preview :books:: https://DiffEngine--88.org.readthedocs.build/en/88/
> [Enhance] Support fast norm controlnet

- README.md
- configs/_base_/datasets/pokemon_blip_wuerstchen.py
- configs/_base_/models/wuerstchen_prior.py
- configs/_base_/models/wuerstchen_prior_lora.py
- configs/wuerstchen/README.md
- configs/wuerstchen/wuerstchen_prior_pokemon_blip.py
- configs/wuerstchen_lora/README.md
- configs/wuerstchen_lora/wuerstchen_prior_lora_pokemon_blip.py
- diffengine/engine/hooks/__init__.py
- diffengine/engine/hooks/lora_save_hook.py
- diffengine/engine/hooks/wuerstchen_save_hook.py
- diffengine/models/editors/__init__.py
- diffengine/models/editors/wuerstchen/__init__.py
- diffengine/models/editors/wuerstchen/efficient_net_encoder.py
- diffengine/models/editors/wuerstchen/wuerstchen_prior.py
- diffengine/models/utils/__init__.py
- diffengine/models/utils/timesteps.py
- docs/source/run_guides/run_wuerstchen.md
- docs/source/run_guides/run_wuerstchen_lora.md
- pyproject.toml
- tests/test_engine/test_hooks/test_lora_save_hook.py
- tests/test_engine/test_hooks/test_wuerstchen_save_hook.py
- tests/test_models/test_editors/test_wuerstchen/test_wuerstchen_prior.py
- tests/test_models/test_utils/test_timesteps.py
[Wuerstchen: An Efficient Architecture for Large-Scale Text-to-Image Diffusion Models](https://arxiv.org/abs/2306.00637)
**Before PR**:
----
:books: Documentation preview :books:: https://DiffEngine--91.org.readthedocs.build/en/91/
> [Feature] Wuerstchen

- README.md
- configs/distill_sd_dreambooth/README.md
- configs/stable_diffusion_dreambooth/README.md
- configs/stable_diffusion_lora/README.md
- docs/source/run_guides/inference.md
- docs/source/run_guides/run_dreambooth.md
- docs/source/run_guides/run_lora.md
Fix LoRA docs.
**Before PR**:
----
:books: Documentation preview :books:: https://DiffEngine--93.org.readthedocs.build/en/93/
> [Fix] LoRA docs

- configs/stable_diffusion_xl/stable_diffusion_xl_pokemon_blip_fast.py
- diffengine/engine/hooks/compile_hook.py
- diffengine/engine/hooks/fast_norm_hook.py
- diffengine/models/editors/deepfloyd_if/deepfloyd_if.py
- diffengine/models/editors/distill_sd/distill_sd_xl.py
- diffengine/models/editors/esd/esd_xl.py
- diffengine/models/editors/instruct_pix2pix/instruct_pix2pix_xl.py
- diffengine/models/editors/ip_adapter/ip_adapter_pipeline.py
- diffengine/models/editors/ip_adapter/ip_adapter_xl.py
- diffengine/models/editors/ssd_1b/ssd_1b.py
- diffengine/models/editors/stable_diffusion/stable_diffusion.py
- diffengine/models/editors/stable_diffusion_controlnet/stable_diffusion_controlnet.py
- diffengine/models/editors/stable_diffusion_xl/stable_diffusion_xl.py
- diffengine/models/editors/stable_diffusion_xl_controlnet/stable_diffusion_xl_controlnet.py
- diffengine/models/editors/t2i_adapter/stable_diffusion_xl_t2i_adapter.py
- diffengine/models/editors/wuerstchen/wuerstchen_prior.py
- tests/test_engine/test_hooks/test_compile_hook.py
- tests/test_engine/test_hooks/test_fast_norm_hook.py
Support `torch.compile` for controlnet.
Support apex fused GN.
**Before PR**:
----
:books: Documentation preview :books:: https://DiffEngine--95.org.readthedocs.build/en/95/
> [Feature] Support compile controlnet and fused GN

- pyproject.toml
Bump v0.3.0.
**Before PR**:
----
:books: Documentation preview :books:: https://DiffEngine--97.org.readthedocs.build/en/97/
> [Bump] v0.3.0

- configs/_base_/datasets/cat_waterpainting_dreambooth_xl.py
- configs/_base_/datasets/waterpainting_xl.py
- configs/debias_estimation_loss/stable_diffusion_xl_pokemon_blip_debias_estimation_loss.py
- configs/input_perturbation/stable_diffusion_xl_pokemon_blip_input_perturbation.py
- configs/ip_adapter/stable_diffusion_xl_pokemon_blip_ip_adapter.py
- configs/ip_adapter/stable_diffusion_xl_pokemon_blip_ip_adapter_plus.py
- configs/lcm/lcm_xl_pokemon_blip.py
- configs/offset_noise/stable_diffusion_xl_pokemon_blip_offset_noise.py
- configs/pyramid_noise/stable_diffusion_xl_pokemon_blip_pyramid_noise.py
- configs/stable_diffusion_xl/stable_diffusion_xl_pokemon_blip.py
- configs/stable_diffusion_xl/stable_diffusion_xl_pokemon_blip_pre_compute.py
- configs/stable_diffusion_xl_dreambooth/README.md
- configs/stable_diffusion_xl_dreambooth/stable_diffusion_xl_dreambooth_lora_cat_waterpainting.py
- configs/stable_diffusion_xl_lora/README.md
- configs/stable_diffusion_xl_lora/stable_diffusion_xl_lora_waterpainting.py
- configs/timesteps_bias/stable_diffusion_xl_pokemon_blip_earlier_bias.py
- configs/timesteps_bias/stable_diffusion_xl_pokemon_blip_later_bias.py
- configs/timesteps_bias/stable_diffusion_xl_pokemon_blip_range_bias.py
- configs/wuerstchen/wuerstchen_prior_pokemon_blip.py
- docs/source/run_guides/run_ip_adapter.md
- docs/source/run_guides/run_lcm.md
- docs/source/run_guides/run_sdxl.md
- docs/source/run_guides/run_wuerstchen.md
- pyproject.toml
[ZipLoRA: Any Subject in Any Style by Effectively Merging LoRAs](https://arxiv.org/abs/2311.13600)
SDXL model learns to produce stylized outputs when fine-tuned on a single example of a reference style using LoRA with a DreamBooth objective.
**Before PR**:
----
:books: Documentation preview :books:: https://DiffEngine--102.org.readthedocs.build/en/102/
> [Feature] Support Style LoRA

- README.md
- configs/_base_/models/stable_diffusion_xl_controlnetxs.py
- configs/stable_diffusion_xl_controlnet/README.md
- configs/stable_diffusion_xl_controlnet_small/README.md
- configs/stable_diffusion_xl_controlnetxs/README.md
- configs/stable_diffusion_xl_controlnetxs/stable_diffusion_xl_controlnetxs_fill50k.py
- diffengine/models/editors/stable_diffusion_xl_controlnet/__init__.py
- diffengine/models/editors/stable_diffusion_xl_controlnet/stable_diffusion_xl_controlnetxs.py
- tests/test_models/test_editors/test_stable_diffusion_xl_controlnet/test_stable_diffusion_xl_controlnetxs.py
[ControlNet-XS](https://vislearn.github.io/ControlNet-XS/)
**Before PR**:
----
:books: Documentation preview :books:: https://DiffEngine--110.org.readthedocs.build/en/110/
> [Feature] Support ControlNetXS

- configs/_base_/datasets/dog_inpaint_multiple_mask.py
- diffengine/datasets/transforms/loading.py
- tests/test_datasets/test_transforms/test_loading.py
Support whole mask for inpainting training.
**Before PR**:
----
📚 Documentation preview 📚: https://DiffEngine--113.org.readthedocs.build/en/113/
> [Feature] Support whole mask

- docs/source/index.rst
- docs/source/run_guides/run_sd.md
- docs/source/run_guides/run_sdxl.md
**Before PR**:
----
📚 Documentation preview 📚: https://DiffEngine--120.org.readthedocs.build/en/120/
> [Enhance] Update docs

- pyproject.toml
**Before PR**:
----
📚 Documentation preview 📚: https://DiffEngine--123.org.readthedocs.build/en/123/
> [Bump] v1.0.0

- README.md
- diffengine/configs/_base_/datasets/pokemon_blip_amused_512.py
- diffengine/configs/_base_/models/amused_512.py
- diffengine/configs/amused/README.md
- diffengine/configs/amused/amused_512_pokemon_blip.py
- diffengine/datasets/transforms/__init__.py
- diffengine/datasets/transforms/processing.py
- diffengine/engine/hooks/__init__.py
- diffengine/engine/hooks/transformer_checkpoint_hook.py
- diffengine/models/editors/__init__.py
- diffengine/models/editors/amused/__init__.py
- diffengine/models/editors/amused/amused.py
- diffengine/models/editors/amused/amused_data_preprocessor.py
- diffengine/models/losses/__init__.py
- diffengine/models/losses/cross_entropy_loss.py
- tests/test_datasets/test_transforms/test_processing.py
- tests/test_engine/test_hooks/test_transformer_checkpoint_hook.py
- tests/test_models/test_editors/test_amused/test_amused.py
- tests/test_models/test_losses.py
[aMUSEd: An Open MUSE Reproduction](https://arxiv.org/abs/2401.01808)
**Before PR**:
----
📚 Documentation preview 📚: https://DiffEngine--125.org.readthedocs.build/en/125/
> [Feature] Support aMUSEd

- README.md
- projects/controlnetxs/README.md
- projects/controlnetxs/_base_/stable_diffusion_xl_controlnetxs.py
- projects/controlnetxs/modules/__init__.py
- projects/controlnetxs/modules/controlnetxs.py
- projects/controlnetxs/modules/pipeline_controlnet_xs_sd_xl.py
- projects/controlnetxs/modules/stable_diffusion_xl_controlnetxs.py
- tests/test_models/test_editors/test_stable_diffusion_controlnet/test_stable_diffusion_controlnet.py
- tests/test_models/test_editors/test_stable_diffusion_xl_controlnet/test_stable_diffusion_xl_controlnet.py
Fix based on diffusers update.
**Before PR**:
----
📚 Documentation preview 📚: https://DiffEngine--127.org.readthedocs.build/en/127/
> [BugFix] ControlNet-XS projects
